### ISSUE TITLE
Should the library pick up AWS_REGION env var?

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aiodynamo#32]
And while on the subject, if the `endpoint` is passed to the `Client`, is the region still strictly necessary?

**Comment by ojii** [comment]
the `region` is required for request signing. Even a local endpoint might verify the signature, so region is definitely necessary.

The region was made an explicit argument since AWS API require it. boto3 has a complex mechanism to determine the region (which is incredibly slow) if none is given, it's not always just an env variable.

A DynamoDB table is identified by its name + region, so making it explicit seems appropriate.
